README更新
elixirjp-slack-com/realworld pull request #22
Opened 2022-01-28 12:57 UTC by TORIFUKUKaiou

ふつう？ に[Installation](https://hexdocs.pm/phoenix/installation.html#content)から進めて、ローカルマシンでイゴかす手順とDockerのみでイゴかす手順をかきました
Dockerのみでイゴかす変更について補足します。

- `docker-compose up`でRunできるようにしてみました
- Dockerfileに`build-essential`をいれたのは、`Bcrypt`のビルドで`make`が必要だったからです
- もっと洗練、厳選できるところがあるかもしれませんがとりあえずmacOS CatalinaとWindows 11でイゴいた内容でプルリクを作りました
- 欠点は、`config/`以下のファイルを変更しないといけないことです

2022-02-02 07:01 UTC, kentaro commented
ありがとうございます！

最初の方に、これはWEB+DB PRESS Vol.127の特集「〜」のサンプルコードです、みたいなのがあるとよさそうです。

2022-02-02 07:02 UTC, kentaro requested changes
最初の方に、これはWEB+DB PRESS Vol.127の特集「〜」のサンプルコードです、みたいなのがあるとよさそうです。

2022-02-02 07:53 UTC, kentaro commented
動作確認もしてみました。ローカルはOK。

Dockerの方が、`docker-compose up`でちゃんとwebロールも上がってるのですが、 http://localhost:4000/articles に接続できず。なんでだろうなあ。

```
realworld-web-1  | [info] Running RealworldWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)
realworld-web-1  | [info] Access RealworldWeb.Endpoint at http://localhost:4000
realworld-web-1  | [watch] build finished, watching for changes...
```

2022-02-02 08:01 UTC, tamanugi commented
ありがとうございます 👍 

IMOですが、あんまり英語である必要がない気がするので、項目とか日本語とかにしてもいいのかな〜って気がしました。

2022-02-02 08:06 UTC, TORIFUKUKaiou commented
@kentaro 
レビューありがとうございます！

config/dev.exs の設定は正しいでしょうか〜？

```diff
config :realworld, RealworldWeb.Endpoint,
   # Binding to loopback ipv4 address prevents access from other machines.
   # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
-  http: [ip: {127, 0, 0, 1}, port: 4000],
+  http: [ip: {0, 0, 0, 0}, port: 4000],
   check_origin: false,
   code_reloader: true,
   debug_errors: true,
```

2022-02-02 08:07 UTC, TORIFUKUKaiou commented
@kentaro @tamanugi 
最初の方に、これはWEB+DB PRESS Vol.127の特集「〜」のサンプルコードです、みたいなの〜　をいれるとともに、無理して英語で書かずに、日本語で書いてみます 😅

2022-02-02 08:19 UTC, mokichi reviewed
私も手元で `docker compose up` 動かしてみましたが、正常に動きました

2022-02-02 08:19 UTC, mokichi commented on README.md
> ++  hostname: "db",
↓のようなコードにして `docker-compose.yml` で環境変数を指定するようにすれば、READMEでの記述をなくせます

```elixir
System.get_env("DB_HOST", "localhost")
```

2022-02-02 08:19 UTC, mokichi commented on README.md
> ++  http: [ip: {0, 0, 0, 0}, port: 4000],
Dockerを使う使わないに関わらず `ip: {0, 0, 0, 0}` にしちゃっても良さそうです

2022-02-02 08:20 UTC, kentaro commented
設定も変えて、`[info] Running RealworldWeb.Endpoint with cowboy 2.9.0 at 0.0.0.0:4000 (http)`となってるんですよねえ。なんだろな。

```diff
diff --git a/config/dev.exs b/config/dev.exs
index 54e312b..b5c6cc7 100644
--- a/config/dev.exs
+++ b/config/dev.exs
@@ -4,7 +4,7 @@ import Config
 config :realworld, Realworld.Repo,
   username: "postgres",
   password: "postgres",
-  hostname: "localhost",
+  hostname: "db",
   database: "realworld_dev",
   show_sensitive_data_on_connection_error: true,
   pool_size: 10
@@ -18,7 +18,7 @@ config :realworld, Realworld.Repo,
 config :realworld, RealworldWeb.Endpoint,
   # Binding to loopback ipv4 address prevents access from other machines.
   # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
-  http: [ip: {127, 0, 0, 1}, port: 4000],
+  http: [ip: {0, 0, 0, 0}, port: 4000],
   check_origin: false,
   code_reloader: true,
   debug_errors: true,
```

2022-02-02 16:27 UTC, TORIFUKUKaiou commented
@kentaro @tamanugi @mokichi 

ご確認ありがとうございます 🙏 🙇 🙏 🙇 🙏 🙇 
2/13 までにはマージできるように対応しておきます。
まずは2/6(日)中には更新しておきます。

2022-02-06 16:16 UTC, TORIFUKUKaiou commented
@kentaro @tamanugi @thehaigo @mokichi 

レビューよろしくお願いします 🙏 🙇 

- READMEを全面的に書き換えました
  - https://github.com/elixirjp-slack-com/realworld/tree/e63696237ffd3e8ffa240681f9b1236afa80cbe6
  - ここでみていただくと見やすいとおもいます
- README中、雑誌のリンク https://gihyo.jp/magazine/wdpress/archive/2022/vol127 はまだページがありません
  - [vol.126](https://gihyo.jp/magazine/wdpress/archive/2022/vol126)から推測してあらかじめいれています
- 表紙画像は元の画像のサイズおおおよそ38%くらいにしています
- 大筋間違ってはいないとおもっています
- なにかお気づきの場合は、[ブランチ](https://github.com/elixirjp-slack-com/realworld/tree/docker-compose)にコミットを追加していただけますでしょうか
  - たぶん、メンションしたみなさんは直接コミットできる設定（アクセス権）になっているとおもっていますが、できないことを言っていたらコメントで指摘をください
  - suggestionでもありがたいです
- データベースの環境変数は、`WEB_DB_PRESS_VOL_127_DB_HOST`というふうに接頭辞を多くつけておくことで、各自がローカルに定義しているものを参照しちゃっていたという可能性を極力減らすようにしました
- 釈迦に説法感が満載ですし、過剰なまでに消しすぎかもしれませんが、前回のレビューで`docker-compose up`で「動かなかった」というコメントがありましたのでまっさらから構築する手順です

```
$ rm -rf deps
$ rm -rf _build
$ docker ps -a

$ docker rm <container ids>
$ docker container prune

$ docker rmi realworld_web

$ docker volume prune

$ docker-compose build --no-cache
$ docker-compose up
```

2022-02-07 02:25 UTC, mokichi approved these changes
@TORIFUKUKaiou 「必要なもの」のところだけ細かいコメント付けましたが、他は問題ないと思います！ 🙏

2022-02-07 02:25 UTC, mokichi commented on README.md
> +- Elixir 1.12 or later
ElixirのバージョンがDockerイメージと違うのと、Erlangのインストールが必要なことも書いたほうが良さそうです

```suggestion
- Elixir 1.13 or later
- Erlang 24.0 or later
```

2022-02-07 02:25 UTC, mokichi commented on README.md
> +- PostgreSQL
```suggestion
- PostgreSQL 13 or later
```

2022-02-07 02:30 UTC, TORIFUKUKaiou commented on README.md
> +- Elixir 1.12 or later
ありがとうございます！

2022-02-07 02:30 UTC, TORIFUKUKaiou commented on README.md
> +- PostgreSQL
ありがとうございます！

2022-02-08 05:48 UTC, kentaro commented
@TORIFUKUKaiou さんはMacで動かしているのですか？Windowsとかについてはどうするのがいいんですかねー。「Macで動かしてるんで、他のOSではそれぞれ頑張ってね」という感じで、前提とする環境を書いておく方がいいように思いました。

2022-02-08 11:20 UTC, TORIFUKUKaiou commented
前提条件を追記

2022-02-08 11:24 UTC, TORIFUKUKaiou commented
@kentaro さん

動作確認できたOSの情報をREADMEに追記しました。

Closeは誤操作だとおもったので Re-open にしましたが、新たに READMEを書かれるということでしたら、このプルリクはCloseにしていただいてもかまいません。

2022-02-08 11:26 UTC, kentaro commented
あれ、間違ってCloseしてましたね！内容OKだと思いあmす！

2022-02-08 11:36 UTC, merged