WIP Chapter5: Phoenix LiveView
elixirjp-slack-com/realworld pull request #4
Opened 2021-12-03 03:17 UTC by mokichi

2021-12-03 23:45 UTC, TORIFUKUKaiou requested changes
chapter5ブランチで動作確認をしてみました。
タグの入力に関するコード追加が必要だとおもいます。
私が勘違いしているだけかもしれません:pray:が、勘違いだったらそれはそれでヨシとさせていただいて、Request changesにてレビュー結果をお戻しします。


![スクリーンショット 2021-12-04 8 42 08](https://user-images.githubusercontent.com/4215723/144686537-908327cd-72f2-4903-95ba-dcd98f485b0a.png)

@tamanugi さんの実装では5章を想定されています。
https://github.com/elixirjp-slack-com/realworld_phoenix_liveview/blob/52da6782045f89c9e3aa06a5f6e8eeef779b6079/lib/realworld_phoenix_liveview_web/live/article_live/form_component.html.heex#L22

https://github.com/elixirjp-slack-com/realworld_phoenix_liveview/commit/7d4bac6263399384271765c857b5faec8de4b2ab

2021-12-03 23:45 UTC, TORIFUKUKaiou commented on .tool-versions
> +erlang 24.1.2
IMHO: 本筋ではありません。このままでよいとおもっています。今朝12/4(土) 08:38、`asdf list all erlang`してみたら`24.1.7`が手に入るようです。私は`24.1.4`を使っていました。

2021-12-04 00:08 UTC, TORIFUKUKaiou reviewed
IMHO
もしかして開発環境による？　のかもしれませんが、
私のマシンで https://github.com/elixirjp-slack-com/realworld/pull/4/commits/2e22b347285c936b6c2cfcb99e02857b2d031398 の時点で、mix formatすると
以下のファイルがフォーマットされていました。
ご確認いただけますでしょうか :pray:

- lib/realworld_web/live/article_live/show.ex
- test/realworld_web/live/article_live_test.exs

```
@@ -1,2 +0,0 @@
-elixir 1.12.3-otp-24
-erlang 24.1.2
diff --git a/lib/realworld_web/live/article_live/show.ex b/lib/realworld_web/live/article_live/show.ex
index f388ebc..f63b156 100644
--- a/lib/realworld_web/live/article_live/show.ex
+++ b/lib/realworld_web/live/article_live/show.ex
@@ -13,14 +13,17 @@ defmodule RealworldWeb.ArticleLive.Show do
   @impl true
   def handle_params(%{"id" => id}, _, socket) do
     article = get_article!(id)
+
     %{
       live_action: action,
       current_user: user
     } = socket.assigns
+
     author_id = article.author_id
 
     if action == :edit && author_id != user.id do
       redirect_path = Routes.article_show_path(socket, :show, article)
+
       {:noreply,
        socket
        |> put_flash(:error, "You can't edit this article")
@@ -39,6 +42,7 @@ defmodule RealworldWeb.ArticleLive.Show do
       article: article,
       current_user: user
     } = socket.assigns
+
     author_id = article.author_id
 
     if author_id != user.id do
@@ -54,11 +58,13 @@ defmodule RealworldWeb.ArticleLive.Show do
   def handle_event("post_comment", %{"comment" => comment_params}, socket) do
     case create_comment(comment_params, socket) do
       {:ok, _} ->
-        article = get_article!(socket.assigns.article.id) 
+        article = get_article!(socket.assigns.article.id)
+
         {:noreply,
          socket
          |> assign(:article, article)
          |> assign(:comment_changeset, change_comment())}
+
       {:error, changeset} ->
         {:noreply, assign(socket, :comment_changeset, changeset)}
     end
diff --git a/test/realworld_web/live/article_live_test.exs b/test/realworld_web/live/article_live_test.exs
index b265251..4db4e1a 100644
--- a/test/realworld_web/live/article_live_test.exs
+++ b/test/realworld_web/live/article_live_test.exs
@@ -28,6 +28,7 @@ defmodule RealworldWeb.ArticleLiveTest do
         author_id: user.id,
         tags_string: "test"
       })
+
     %{article_with_tag: article}
   end
 
@@ -45,7 +46,11 @@ defmodule RealworldWeb.ArticleLiveTest do
       assert html =~ article.body
     end
 
-    test "searches articles by tag", %{conn: conn, article: article, article_with_tag: article_with_tag} do
+    test "searches articles by tag", %{
+      conn: conn,
+      article: article,
+      article_with_tag: article_with_tag
+    } do
       {:ok, index_live, _html} = live(conn, Routes.article_index_path(conn, :index))
 
       html =
```

2021-12-04 14:13 UTC, mokichi commented
> タグの入力に関するコード追加が必要だとおもいます。

追加しました

> mix formatすると
> 以下のファイルがフォーマットされていました。

実行しました

2021-12-05 02:45 UTC, TORIFUKUKaiou approved these changes
LGTM

記事にタグをつけて保存する対応と`mix format`ありがとうございました。
Approveします。

どなたに見てもらうのがよいのかわからない動作がありましたのでIssueをあげておきました。
Slackでもお知らせします。
https://github.com/elixirjp-slack-com/realworld/issues/5

2021-12-05 14:38 UTC, tamanugi commented
対応ありがとうございました 🙇 

動作は問題なさそうでした。
サンプルコードだけでもRealworldの見た目を実装しておきたいなって思ったのですが、紙面とズレるので微妙ですかね。。。

2021-12-06 02:07 UTC, mokichi commented
@TORIFUKUKaiou @tamanugi #5 の件にしろ見た目の実装にしろ、別PRでの対応でいいんじゃないでしょうか？

2021-12-06 02:28 UTC, tamanugi commented
@mokichi 

別PRで問題ないと思います！
僕の方で対応しますmm

2021-12-06 02:28 UTC, tamanugi approved these changes

2021-12-06 04:37 UTC, merged